const data = [
  {
    Title: "Evil Dead Rise",
    Year: "2023",
    Rated: "R",
    Released: "21 Apr 2023",
    Runtime: "96 min",
    Genre: "Horror",
    Director: "Lee Cronin",
    Writer: "Lee Cronin",
    Actors: "Mirabai Pease, Richard Crouchley, Anna-Maree Thomas",
    Plot: "A twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
    Language: "English",
    Country: "United States, New Zealand, Ireland",
    Awards: "2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmZiN2VmMjktZDE5OC00ZWRmLWFlMmEtYWViMTY4NjM3ZmNkXkEyXkFqcGdeQXVyMTI2MTc2ODM3._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.6/10" },
      { Source: "Rotten Tomatoes", Value: "83%" },
      { Source: "Metacritic", Value: "69/100" },
    ],
    Metascore: "69",
    imdbRating: "6.6",
    imdbVotes: "92,536",
    imdbID: "tt13345606",
    Type: "movie",
    DVD: "09 May 2023",
    BoxOffice: "$67,233,054",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "War",
    Year: "2019",
    Rated: "Not Rated",
    Released: "02 Oct 2019",
    Runtime: "154 min",
    Genre: "Action, Adventure, Thriller",
    Director: "Siddharth Anand",
    Writer: "Siddharth Anand, Aditya Chopra, Shridhar Raghavan",
    Actors: "Hrithik Roshan, Tiger Shroff, Vaani Kapoor",
    Plot: "An Indian soldier chases after his mentor who has gone rogue following an unexpected kill.",
    Language: "Hindi, Tamil, Telugu",
    Country: "India",
    Awards: "22 wins & 17 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTlmNDMzOWQtYzg4Ny00OWQ0LWFhN2MtNmQ2MDczZGZhNTU5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.5/10" },
      { Source: "Rotten Tomatoes", Value: "71%" },
    ],
    Metascore: "N/A",
    imdbRating: "6.5",
    imdbVotes: "29,613",
    imdbID: "tt7430722",
    Type: "movie",
    DVD: "28 Nov 2019",
    BoxOffice: "$4,654,000",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Brahmastra Part One: Shiva",
    Year: "2022",
    Rated: "M",
    Released: "09 Sep 2022",
    Runtime: "167 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Ayan Mukerji",
    Writer: "Hussain Dalal, Ayan Mukerji",
    Actors: "Amitabh Bachchan, Ranbir Kapoor, Alia Bhatt",
    Plot: "This is the story of Shiva who sets out in search of love and self-discovery. During his journey, he has to face many evil forces that threaten our existence.",
    Language: "Hindi, English",
    Country: "India",
    Awards: "24 wins & 35 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDEyNjA0MWItY2IxMi00YTZjLTkxOGItNWIwOGQ2OTZmNTg2XkEyXkFqcGdeQXVyMTYyNjAzOTUx._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "5.6/10" },
      { Source: "Rotten Tomatoes", Value: "52%" },
      { Source: "Metacritic", Value: "57/100" },
    ],
    Metascore: "57",
    imdbRating: "5.6",
    imdbVotes: "108,647",
    imdbID: "tt6277462",
    Type: "movie",
    DVD: "07 Dec 2022",
    BoxOffice: "$7,839,108",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Vikram Vedha",
    Year: "2022",
    Rated: "Not Rated",
    Released: "30 Sep 2022",
    Runtime: "160 min",
    Genre: "Action, Crime, Drama",
    Director: "Gayatri, Pushkar",
    Writer: "Benazir Ali Fida, Gayatri, Manoj Muntashir",
    Actors: "Saif Ali Khan, Hrithik Roshan, Radhika Apte",
    Plot: "A tough police officer sets out to track down and kill an equally tough gangster.",
    Language: "Hindi",
    Country: "India",
    Awards: "3 wins & 13 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTEyYjgzNmUtM2QyYi00MWMwLWExMDctZmY1NmZhNGY5MWNiXkEyXkFqcGdeQXVyOTcwMTQxMTM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.1/10" },
      { Source: "Rotten Tomatoes", Value: "73%" },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "20,898",
    imdbID: "tt13131350",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$1,589,362",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Karthikeya 2",
    Year: "2022",
    Rated: "N/A",
    Released: "13 Aug 2022",
    Runtime: "150 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Chandoo Mondeti",
    Writer: "Chandoo Mondeti, Gopal Ram",
    Actors: "Nikhil Siddharth, Anupama Parameswaran, Srinivasa Reddy",
    Plot: "A sequel to mystic thriller Karthikeya (2014), which deals with the personal problems of Karthik and how he comes out of them. His pursuit of the truth leads him to find out the power of Indian ancient system and Tatva of Lord Sri...",
    Language: "Telugu",
    Country: "India",
    Awards: "1 win & 1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzFhZTE0NDAtMWNiYy00NDEwLWJkODctZWExZmIwZmM2ZjM5XkEyXkFqcGdeQXVyMTIyNzY0NTMx._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.0/10" }],
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "63,426",
    imdbID: "tt13664684",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Drishyam 2",
    Year: "2021",
    Rated: "N/A",
    Released: "19 Feb 2021",
    Runtime: "152 min",
    Genre: "Crime, Drama, Thriller",
    Director: "Jeethu Joseph",
    Writer: "Jeethu Joseph",
    Actors: "Mohanlal, Meena, Ansiba",
    Plot: "A gripping tale of an investigation and a family which is threatened by it. Will Georgekutty be able to protect his family this time?",
    Language: "Malayalam",
    Country: "India",
    Awards: "10 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2RiZDVjYWEtZGNhYy00ZGU0LTgwZjMtZTJmNmMyNGQ5NGYyXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "88%" },
    ],
    Metascore: "N/A",
    imdbRating: "8.4",
    imdbVotes: "39,220",
    imdbID: "tt12361178",
    Type: "movie",
    DVD: "21 Feb 2021",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Thank God",
    Year: "2022",
    Rated: "N/A",
    Released: "25 Oct 2022",
    Runtime: "121 min",
    Genre: "Comedy, Fantasy",
    Director: "Indra Kumar",
    Writer: "Aakash Kaushik, Anders Matthesen, Samuthirakani",
    Actors: "Sidharth Malhotra, Ajay Devgn, Rakul Preet Singh",
    Plot: 'An egoistic real estate broker in huge debts, meets with an accident.God appears in front of him and informs him that he will have to play a "GAME OF LIFE". If he win, he will be sent back to earth and if not, he will be sent to h...',
    Language: "Hindi",
    Country: "India",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDc0NzU5MzMtNDFkMC00MTNkLWE2MzMtMmYwMzdkY2EzZDVhXkEyXkFqcGdeQXVyMTE0MTY2Mzk2._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "5.6/10" },
      { Source: "Rotten Tomatoes", Value: "29%" },
    ],
    Metascore: "N/A",
    imdbRating: "5.6",
    imdbVotes: "11,567",
    imdbID: "tt13795296",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "PK",
    Year: "2014",
    Rated: "Not Rated",
    Released: "19 Dec 2014",
    Runtime: "153 min",
    Genre: "Comedy, Drama, Sci-Fi",
    Director: "Rajkumar Hirani",
    Writer: "Rajkumar Hirani, Abhijat Joshi",
    Actors: "Aamir Khan, Anushka Sharma, Sanjay Dutt",
    Plot: "An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate the impact of there religious views on there people.",
    Language: "Hindi",
    Country: "India",
    Awards: "20 wins & 23 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTYzOTE2NjkxN15BMl5BanBnXkFtZTgwMDgzMTg0MzE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.1/10" },
      { Source: "Rotten Tomatoes", Value: "78%" },
    ],
    Metascore: "N/A",
    imdbRating: "8.1",
    imdbVotes: "193,804",
    imdbID: "tt2338151",
    Type: "movie",
    DVD: "26 Mar 2017",
    BoxOffice: "$10,616,104",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Pathaan",
    Year: "2023",
    Rated: "Not Rated",
    Released: "25 Jan 2023",
    Runtime: "146 min",
    Genre: "Action, Adventure, Thriller",
    Director: "Siddharth Anand",
    Writer: "Shridhar Raghavan, Abbas Tyrewala, Siddharth Anand",
    Actors: "Shah Rukh Khan, Deepika Padukone, John Abraham",
    Plot: "An Indian agent races against a doomsday clock as a ruthless mercenary, with a bitter vendetta, mounts an apocalyptic attack against the country.",
    Language: "Hindi, English, Russian",
    Country: "India",
    Awards: "3 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMThkZmNlMzQtZmU4Ny00YzhkLWE5YWYtOGJjNjRjODNjMzZkXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "5.9/10" },
      { Source: "Metacritic", Value: "47/100" },
    ],
    Metascore: "47",
    imdbRating: "5.9",
    imdbVotes: "140,088",
    imdbID: "tt12844910",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$17,487,476",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Total Dhamaal",
    Year: "2019",
    Rated: "Not Rated",
    Released: "22 Feb 2019",
    Runtime: "130 min",
    Genre: "Action, Adventure, Comedy",
    Director: "Indra Kumar",
    Writer: "Paritosh Painter, Ved Prakash, Bunty Rathore",
    Actors: "Ajay Devgn, Anil Kapoor, Madhuri Dixit",
    Plot: "A group of people learn about a hidden treasure and then they race to find it and claim it.",
    Language: "Hindi",
    Country: "India",
    Awards: "1 win & 3 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTdiN2Q2MGUtYWRjMi00M2Y2LWEzOTYtOTA3NjNiMGMzNmFhXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "4.2/10" },
      { Source: "Rotten Tomatoes", Value: "30%" },
    ],
    Metascore: "N/A",
    imdbRating: "4.2",
    imdbVotes: "7,415",
    imdbID: "tt7639372",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$2,167,632",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Luka Chuppi",
    Year: "2019",
    Rated: "Not Rated",
    Released: "01 Mar 2019",
    Runtime: "126 min",
    Genre: "Comedy, Romance",
    Director: "Laxman Utekar",
    Writer: "Rohan Shankar",
    Actors: "Kartik Aaryan, Kriti Sanon, Aparshakti Khurana",
    Plot: "Pretending to be married in order to cohabitate, a small-town couple lands in endless awkward situations to hide the truth from their orthodox families.",
    Language: "Hindi",
    Country: "India",
    Awards: "2 wins & 5 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2MwM2ZhNTItMzkwNi00MTQxLTljMDAtZTk1YmU2M2YzNGVmXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.3/10" },
      { Source: "Rotten Tomatoes", Value: "31%" },
    ],
    Metascore: "N/A",
    imdbRating: "6.3",
    imdbVotes: "12,555",
    imdbID: "tt8908002",
    Type: "movie",
    DVD: "07 Jun 2019",
    BoxOffice: "$1,042,905",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Student of the Year 2",
    Year: "2019",
    Rated: "Not Rated",
    Released: "10 May 2019",
    Runtime: "146 min",
    Genre: "Action, Comedy, Drama",
    Director: "Punit Malhotra",
    Writer: "Arshad Syed, Karan Johar",
    Actors: "Tiger Shroff, Ananya Panday, Tara Sutaria",
    Plot: "A student must face off against bullies and overcome hurdles, both academic and romantic, to win his college's coveted Student of the Year trophy.",
    Language: "Hindi",
    Country: "India",
    Awards: "6 wins & 6 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmFiNjRlODUtNjRiZi00ZDQ0LTk3ZDItZDhjNmU5N2RkNGNjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "2.2/10" },
      { Source: "Rotten Tomatoes", Value: "6%" },
    ],
    Metascore: "N/A",
    imdbRating: "2.2",
    imdbVotes: "21,562",
    imdbID: "tt7255568",
    Type: "movie",
    DVD: "27 Aug 2019",
    BoxOffice: "$778,566",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Fast X",
    Year: "2023",
    Rated: "PG-13",
    Released: "19 May 2023",
    Runtime: "141 min",
    Genre: "Action, Adventure, Crime",
    Director: "Louis Leterrier",
    Writer: "Dan Mazeau, Justin Lin, Zach Dean",
    Actors: "Vin Diesel, Michelle Rodriguez, Jason Statham",
    Plot: "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
    Language: "English",
    Country: "United States, China",
    Awards: "2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzZmOTU1ZTEtYzVhNi00NzQxLWI5ZjAtNWNhNjEwY2E3YmZjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "5.9/10" },
      { Source: "Rotten Tomatoes", Value: "57%" },
      { Source: "Metacritic", Value: "56/100" },
    ],
    Metascore: "56",
    imdbRating: "5.9",
    imdbVotes: "74,378",
    imdbID: "tt5433140",
    Type: "movie",
    DVD: "09 Jun 2023",
    BoxOffice: "$145,689,435",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avatar: The Way of Water",
    Year: "2022",
    Rated: "PG-13",
    Released: "16 Dec 2022",
    Runtime: "192 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "James Cameron",
    Writer: "James Cameron, Rick Jaffa, Amanda Silver",
    Actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
    Plot: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 63 wins & 131 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.6/10" },
      { Source: "Rotten Tomatoes", Value: "76%" },
      { Source: "Metacritic", Value: "67/100" },
    ],
    Metascore: "67",
    imdbRating: "7.6",
    imdbVotes: "426,050",
    imdbID: "tt1630029",
    Type: "movie",
    DVD: "28 Mar 2023",
    BoxOffice: "$684,075,767",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avengers: Endgame",
    Year: "2019",
    Rated: "PG-13",
    Released: "26 Apr 2019",
    Runtime: "181 min",
    Genre: "Action, Adventure, Drama",
    Director: "Anthony Russo, Joe Russo",
    Writer: "Christopher Markus, Stephen McFeely, Stan Lee",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    Plot: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    Language: "English, Japanese, Xhosa, German",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 70 wins & 133 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "78/100" },
    ],
    Metascore: "78",
    imdbRating: "8.4",
    imdbVotes: "1,190,338",
    imdbID: "tt4154796",
    Type: "movie",
    DVD: "30 Jul 2019",
    BoxOffice: "$858,373,000",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Black Phone",
    Year: "2021",
    Rated: "R",
    Released: "24 Jun 2022",
    Runtime: "103 min",
    Genre: "Horror, Thriller",
    Director: "Scott Derrickson",
    Writer: "Joe Hill, Scott Derrickson, C. Robert Cargill",
    Actors: "Mason Thames, Madeleine McGraw, Ethan Hawke",
    Plot: "After being abducted by a child killer and locked in a soundproof basement, a 13-year-old boy starts receiving calls on a disconnected phone from the killer's previous victims.",
    Language: "English",
    Country: "United States",
    Awards: "6 wins & 16 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMWQxOGJlNTUtYTc1YS00NDkyLWExZjItMTFiYWEzMjAzYTdjXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.9/10" },
      { Source: "Rotten Tomatoes", Value: "83%" },
      { Source: "Metacritic", Value: "65/100" },
    ],
    Metascore: "65",
    imdbRating: "6.9",
    imdbVotes: "167,820",
    imdbID: "tt7144666",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$90,123,230",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Spider-Man: No Way Home",
    Year: "2021",
    Rated: "PG-13",
    Released: "17 Dec 2021",
    Runtime: "148 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Jon Watts",
    Writer: "Chris McKenna, Erik Sommers, Stan Lee",
    Actors: "Tom Holland, Zendaya, Benedict Cumberbatch",
    Plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 35 wins & 70 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "93%" },
      { Source: "Metacritic", Value: "71/100" },
    ],
    Metascore: "71",
    imdbRating: "8.2",
    imdbVotes: "809,401",
    imdbID: "tt10872600",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$814,115,070",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Black Panther",
    Year: "2018",
    Rated: "PG-13",
    Released: "16 Feb 2018",
    Runtime: "134 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Ryan Coogler",
    Writer: "Ryan Coogler, Joe Robert Cole, Stan Lee",
    Actors: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o",
    Plot: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    Language: "English, Swahili, Nama, Xhosa, Korean",
    Country: "United States",
    Awards: "Won 3 Oscars. 117 wins & 282 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.3/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "88/100" },
    ],
    Metascore: "88",
    imdbRating: "7.3",
    imdbVotes: "806,010",
    imdbID: "tt1825683",
    Type: "movie",
    DVD: "02 May 2018",
    BoxOffice: "$700,426,566",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lost City",
    Year: "2022",
    Rated: "PG-13",
    Released: "25 Mar 2022",
    Runtime: "112 min",
    Genre: "Action, Adventure, Comedy",
    Director: "Aaron Nee, Adam Nee",
    Writer: "Oren Uziel, Dana Fox, Adam Nee",
    Actors: "Sandra Bullock, Channing Tatum, Daniel Radcliffe",
    Plot: "A reclusive romance novelist on a book tour with her cover model gets swept up in a kidnapping attempt that lands them both in a cutthroat jungle adventure.",
    Language: "English, Spanish, Latin, French",
    Country: "United States",
    Awards: "3 wins & 5 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.1/10" },
      { Source: "Rotten Tomatoes", Value: "79%" },
      { Source: "Metacritic", Value: "60/100" },
    ],
    Metascore: "60",
    imdbRating: "6.1",
    imdbVotes: "135,812",
    imdbID: "tt13320622",
    Type: "movie",
    DVD: "10 May 2022",
    BoxOffice: "$105,344,029",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
